name: app
type: php:8.1
# to find the supported versions for the 'nodejs' type.
type: 'nodejs:18'
build:
    flavor: composer
disk: 1024

# Renseignez les variables d'environnement pour votre application Symfony.
variables:
    php:
        APP_ENV: 'prod'
        APP_DEBUG: '0'

# les dependances
dependencies:
    php:
        composer/composer: "^2"

# Configurez les relations entre les services (bases de données, cache, etc.).
#relationships:
    #database: "database:mysql"
    #rediscache: "rediscache:redis"

# Configurez les processus de déploiement et de build.
hooks:
    build: |
        set -e
        composer install --no-dev --optimize-autoloader
        yarn install
    deploy: |
        set -e
        bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
        yarn run build
        bin/console cache:clear

# Configurez les chemins pour les fichiers partagés entre les déploiements.
mounts:
    '/var': { source: local, source_path: var }
    '/public/uploads': { source: local, source_path: public/uploads }

# Configurez la configuration du serveur web.
web:
    locations:
        '/':
            root: 'public'
            passthru: '/index.php'
            index:
                - index.php
            rules:
                \.php$:
                    allow: false
                \.js$:
                    allow: true
                \.css$:
                    allow: true
                \.woff$:
                    allow: true
                \.jpg$:
                    allow: true
                \.png$:
                    allow: true
  commands: 
    start: "node index.js"
